server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL:update}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
        show_sql: ${SHOW_SQL:true}
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

  jackson:
    property-naming-strategy: SNAKE_CASE

aws:
  access-token: ${AWS_ACCESS_TOKEN}
  secret-key: ${AWS_SECRET_KEY}
  ses-source: ${AWS_SES_SOURCE}
  region: ${AWS_REGIONS}